services:
  my-service:
    image: xdash-docker-image
    container_name: orin-alt-container
    hostname: ${HOSTNAME}  # Uses the current hostname of the system
    privileged: true  # Equivalent to --privileged flag
    network_mode: "host" # Expose the container to the network
    volumes:
      - "/proc/device-tree/compatible:/proc/device-tree/compatible:ro"
      - "/xbot/config:/xbot/config"
      - "/dev:/dev"
      - "/home/xbot/Alt:/xbot/Alt"
    # command: ["python", "pathplanning/nmc/fastMarchingMethodRPC.py"]
    command: ["python", "orinProcess.py"]
